// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDeX8xnjPTkGo5Uk4QQCZZh-1coJHtl8jo',
    appId: '1:550032225865:web:4d21af9d914a44779f3198',
    messagingSenderId: '550032225865',
    projectId: 'fir-e-s-c13e3',
    authDomain: 'fir-e-s-c13e3.firebaseapp.com',
    databaseURL: 'https://fir-e-s-c13e3-default-rtdb.firebaseio.com',
    storageBucket: 'fir-e-s-c13e3.appspot.com',
    measurementId: 'G-VYW00EWZ4J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSLSYGm19MBQGj969cSGY0qq7t3NsGzvE',
    appId: '1:550032225865:android:53441d8447a478599f3198',
    messagingSenderId: '550032225865',
    projectId: 'fir-e-s-c13e3',
    databaseURL: 'https://fir-e-s-c13e3-default-rtdb.firebaseio.com',
    storageBucket: 'fir-e-s-c13e3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-iyiVwYSfVMtNjWTDdr4V_ixWboQ0M98',
    appId: '1:550032225865:ios:07e6ee61a6006c9f9f3198',
    messagingSenderId: '550032225865',
    projectId: 'fir-e-s-c13e3',
    databaseURL: 'https://fir-e-s-c13e3-default-rtdb.firebaseio.com',
    storageBucket: 'fir-e-s-c13e3.appspot.com',
    iosClientId: '550032225865-eapesmdv4tf9e2dkrsvttj2ampb8oopg.apps.googleusercontent.com',
    iosBundleId: 'com.example.ses',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-iyiVwYSfVMtNjWTDdr4V_ixWboQ0M98',
    appId: '1:550032225865:ios:07e6ee61a6006c9f9f3198',
    messagingSenderId: '550032225865',
    projectId: 'fir-e-s-c13e3',
    databaseURL: 'https://fir-e-s-c13e3-default-rtdb.firebaseio.com',
    storageBucket: 'fir-e-s-c13e3.appspot.com',
    iosClientId: '550032225865-eapesmdv4tf9e2dkrsvttj2ampb8oopg.apps.googleusercontent.com',
    iosBundleId: 'com.example.ses',
  );
}
